// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for cfattributes resource attributes.
type ResourceAttributesConfig struct {
	CloudfoundryAppAnnotationsX         ResourceAttributeConfig `mapstructure:"cloudfoundry.app.annotations.X"`
	CloudfoundryAppCreated              ResourceAttributeConfig `mapstructure:"cloudfoundry.app.created"`
	CloudfoundryAppLabelsX              ResourceAttributeConfig `mapstructure:"cloudfoundry.app.labels.X"`
	CloudfoundryAppLifecycleBuildpacksI ResourceAttributeConfig `mapstructure:"cloudfoundry.app.lifecycle.buildpacks.I"`
	CloudfoundryAppLifecycleStack       ResourceAttributeConfig `mapstructure:"cloudfoundry.app.lifecycle.stack"`
	CloudfoundryAppLifecycleType        ResourceAttributeConfig `mapstructure:"cloudfoundry.app.lifecycle.type"`
	CloudfoundryAppName                 ResourceAttributeConfig `mapstructure:"cloudfoundry.app.name"`
	CloudfoundryAppState                ResourceAttributeConfig `mapstructure:"cloudfoundry.app.state"`
	CloudfoundryAppUpdated              ResourceAttributeConfig `mapstructure:"cloudfoundry.app.updated"`
	CloudfoundryOrgAnnotationsX         ResourceAttributeConfig `mapstructure:"cloudfoundry.org.annotations.X"`
	CloudfoundryOrgLabelsX              ResourceAttributeConfig `mapstructure:"cloudfoundry.org.labels.X"`
	CloudfoundryOrgName                 ResourceAttributeConfig `mapstructure:"cloudfoundry.org.name"`
	CloudfoundrySpaceAnnotationsX       ResourceAttributeConfig `mapstructure:"cloudfoundry.space.annotations.X"`
	CloudfoundrySpaceLabelsX            ResourceAttributeConfig `mapstructure:"cloudfoundry.space.labels.X"`
	CloudfoundrySpaceName               ResourceAttributeConfig `mapstructure:"cloudfoundry.space.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		CloudfoundryAppAnnotationsX: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppCreated: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppLabelsX: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppLifecycleBuildpacksI: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppLifecycleStack: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppLifecycleType: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppName: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppState: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryAppUpdated: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudfoundryOrgAnnotationsX: ResourceAttributeConfig{
			Enabled: false,
		},
		CloudfoundryOrgLabelsX: ResourceAttributeConfig{
			Enabled: false,
		},
		CloudfoundryOrgName: ResourceAttributeConfig{
			Enabled: false,
		},
		CloudfoundrySpaceAnnotationsX: ResourceAttributeConfig{
			Enabled: false,
		},
		CloudfoundrySpaceLabelsX: ResourceAttributeConfig{
			Enabled: false,
		},
		CloudfoundrySpaceName: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}
