// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				CloudfoundryAppAnnotationsX:         ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppCreated:              ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppLabelsX:              ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppLifecycleBuildpacksI: ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppLifecycleStack:       ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppLifecycleType:        ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppName:                 ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppState:                ResourceAttributeConfig{Enabled: true},
				CloudfoundryAppUpdated:              ResourceAttributeConfig{Enabled: true},
				CloudfoundryOrgAnnotationsX:         ResourceAttributeConfig{Enabled: true},
				CloudfoundryOrgLabelsX:              ResourceAttributeConfig{Enabled: true},
				CloudfoundryOrgName:                 ResourceAttributeConfig{Enabled: true},
				CloudfoundrySpaceAnnotationsX:       ResourceAttributeConfig{Enabled: true},
				CloudfoundrySpaceLabelsX:            ResourceAttributeConfig{Enabled: true},
				CloudfoundrySpaceName:               ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				CloudfoundryAppAnnotationsX:         ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppCreated:              ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppLabelsX:              ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppLifecycleBuildpacksI: ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppLifecycleStack:       ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppLifecycleType:        ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppName:                 ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppState:                ResourceAttributeConfig{Enabled: false},
				CloudfoundryAppUpdated:              ResourceAttributeConfig{Enabled: false},
				CloudfoundryOrgAnnotationsX:         ResourceAttributeConfig{Enabled: false},
				CloudfoundryOrgLabelsX:              ResourceAttributeConfig{Enabled: false},
				CloudfoundryOrgName:                 ResourceAttributeConfig{Enabled: false},
				CloudfoundrySpaceAnnotationsX:       ResourceAttributeConfig{Enabled: false},
				CloudfoundrySpaceLabelsX:            ResourceAttributeConfig{Enabled: false},
				CloudfoundrySpaceName:               ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
